### PR TITLE
Fix npm initializer

### LINKED ISSUE #328: npm initializer doesn't call (or import) `mkNpmProject` correctly

### LINKED ISSUE #329: npm initializer doesn't work for projects that contain dashes

### PR DESCRIPTION
**Pull request by alexdavid**
Resolves #328
Resolves #329

### CODE REVIEW

File: test/spec/InitSpec.hs [hunk 1]
```diff
@@ -64,6 +65,23 @@ spec = do
...
+                "name": "my-project",
+                "scripts": {
+                  "start": "echo starting my project..."
+                }
+              }
+            |]
+          output <- runGarn ["init"] "" repoDir Nothing
+          stderr output `shouldBe` "[garn] Creating a garn.ts file\n"
+          output <- runGarn ["run", "myProject.start"] "" repoDir Nothing
+          stdout output `shouldContain` "starting my project..."
```
Comment (soenkehahn) [inline test/spec/InitSpec.hs:83]: Very nice!

**Review by soenkehahn — APPROVED** [review]
