### PR TITLE
Prevent exporting addCheck directly

### LINKED ISSUE #223: Exporting foo.addCheck("check") silently fails
`addCheck("blah")` doesn't return a Project, but instead a template literal that returns a project. So when you forget to (or don't know that you should) call the template literal, you no longer get the project that you thought you had, without any warnings or explanations.

### PR DESCRIPTION
**Pull request by alexdavid**
Resolves #223

### CODE REVIEW

File: src/Garn.hs [hunk 1]
```diff
@@ -2,24 +2,23 @@
 
 module Garn
   ( Env (..),
-    run,
     readOptionsAndConfig,
     runWith,
+    run,
   )
```
Comment (soenkehahn) [inline src/Garn.hs:8]: I think we might be able to export less items here, since we're not using them in tests anymore.

File: src/Garn.hs [hunk 2]
```diff
@@ -28,11 +27,12 @@ data Env = Env
...
-run :: IO ()
-run = do
-  env <- productionEnv
-  options <- readOptionsAndConfig
-  runWith env options
+run :: Env -> IO ()
+run env =
+  (readOptionsAndConfig >>= runWith env)
+    `catch` \(Garn.Errors.UserError err) -> do
+      hPutStrLn stderr $ "[garn] " <> err
```
Comment (soenkehahn) [inline src/Garn.hs:34]:
```suggestion
      hPutStrLn stderr $ "[garn] Error: " <> err
```

To distinguish this from only informational output. TIOLI.

File: ts/internal/may_not_export.ts [hunk 3]
```diff
@@ -0,0 +1,42 @@
...
+ *
+ * The reason for this is to catch potential mistakes like the following:
+ * ```typescript
+ * export const myProject = getProjectSomehow().addCheck("my-test")
+ * ```
+ *
+ * The above example is missing the call on the tag template literal function
+ * returned by `addCheck`.
+ */
+export function markAsMayNotExprt(
```
Comment (soenkehahn) [inline ts/internal/may_not_export.ts:18]:
```suggestion
export function markAsMayNotExport(
```

File: ts/internal/may_not_export.ts [hunk 4]
```diff
@@ -0,0 +1,42 @@
...
+  // deno-lint-ignore ban-types
+  value: object,
+  reason: (exportName: string) => string
+) {
+  // @ts-expect-error - SAFETY: typescript does not allow setting
+  // `MAY_NOT_EXPORT` on T here. However, it is safe to set arbitrary keys on
+  // non-primative types which `value: object` enforces
```
Comment (soenkehahn) [inline ts/internal/may_not_export.ts:25]:
```suggestion
  // non-primative types, which `value: object` enforces.
```

File: ts/internal/may_not_export.ts [hunk 5]
```diff
@@ -0,0 +1,42 @@
...
+  value[MAY_NOT_EXPORT] = reason;
+}
+
+/**
+ * Throws a runtime error if the passed value has been marked as may not export
+ * using `markAsMayNotExprt`.
```
Comment (soenkehahn) [inline ts/internal/may_not_export.ts:31]:
```suggestion
 * using `markAsMayNotExport`.
```

**Review by soenkehahn — APPROVED** [review]
Left some comments. Otherwise LGTM.

Also, since this is a breaking change, should it bump the ts lib version?

(There's also #264 in flight. So -- if that gets in first -- this has to bump based on that.)

**Review by soenkehahn — APPROVED** [review]
